env:
  NODE_VERSION: '14'

name: github pages

on:
  push:
    branches:
      - v3  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node packages
        run: npm install

      - name: Build
        run: bin/build

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: github.ref == 'refs/heads/v2'
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
